# Configuration for PR Labeler
# Add 'component' labels based on the modified files

component/frontend:
  - project/**/*
  - project/*

component/infrastructure:
  - .gitignore
  - .github/**/*

component/ci-cd:
  - .github/workflows/**/*

component/dependencies:
  - package.json
  - package-lock.json
  - yarn.lock
  - project/package.json
  - project/package-lock.json

component/documentation:
  - '**/*.md'
  - docs/**/*

component/tests:
  - '**/*.test.js'
  - '**/*.test.ts'
  - '**/*.test.jsx'
  - '**/*.test.tsx'
  - '**/*.spec.js'
  - '**/*.spec.ts'
  - '**/*.spec.jsx'
  - '**/*.spec.tsx'
  - project/cypress/**/*

component/config:
  - '**/*.json'
  - '**/*.yaml'
  - '**/*.yml'
  - '**/*.config.js'
  - '**/*.config.ts'
  - .env.example

component/api:
  - project/src/api/**/*
  - project/src/services/**/*

component/security:
  - '**/*security*'
  - project/src/utils/auth.ts

priority/high:
  - project/src/pages/**/*
  - project/src/components/Auth/**/*

priority/security:
  - project/src/utils/auth.js
  - project/src/context/AuthContext.js