services:
  - type: web
    name: speedtest-app
    env: php
    plan: free
    buildCommand: cd project && npm install && npm run build
    startCommand: php -S 0.0.0.0:$PORT server.php
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: speedtest-app
          property: host
      - key: VITE_WS_URL
        fromService:
          type: web
          name: speedtest-app
          property: host
    healthCheckPath: /health